name: Deploy HTML to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        id: setup-ssh
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Archive files
        run: |
          echo "Archiving files"
          tar --exclude='.git*' --exclude='deploy.tar.gz' -czf deploy.tar.gz -C ${{ github.workspace }} .

      - name: Copy archive via SCP
        run: |
          echo "Copying archive via SCP"
          scp -o StrictHostKeyChecking=no -P 21098 deploy.tar.gz benmbrym@68.65.122.80:/home/benmbrym/deploy.tar.gz
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Extract archive on server
        run: |
          echo "Extracting archive on server"
          ssh -o StrictHostKeyChecking=no -p 21098 benmbrym@68.65.122.80 'tar xzf /home/benmbrym/deploy.tar.gz -C /home/benmbrym/test && rm /home/benmbrym/deploy.tar.gz'
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: SSH Command (Optional)
        run: |
          echo "Running SSH command"
          ssh -o StrictHostKeyChecking=no -p 21098 benmbrym@68.65.122.80 'bash -s' < ./deploy_script.sh  # Optional, if you need to run a script on the server after extracting files
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
